/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// CaptureCheckoutRequest
    /// </summary>
    [DataContract(Name = "CaptureCheckoutRequest")]
    public partial class CaptureCheckoutRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureCheckoutRequest" /> class.
        /// </summary>
        /// <param name="merchantOrderId">merchantOrderId.</param>
        /// <param name="expectedTotalAmount">expectedTotalAmount.</param>
        /// <param name="currency">currency.</param>
        /// <param name="metadata">metadata.</param>
        public CaptureCheckoutRequest(string merchantOrderId = default, int expectedTotalAmount = default, string currency = default, Dictionary<string, Object> metadata = default)
        {
            this.MerchantOrderId = merchantOrderId;
            this.ExpectedTotalAmount = expectedTotalAmount;
            this.Currency = currency;
            this.Metadata = metadata;
        }

        /// <summary>
        /// Gets or Sets MerchantOrderId
        /// </summary>
        [DataMember(Name = "merchant_order_id", EmitDefaultValue = true)]
        public string MerchantOrderId { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedTotalAmount
        /// </summary>
        [DataMember(Name = "expected_total_amount", EmitDefaultValue = false)]
        public long ExpectedTotalAmount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaptureCheckoutRequest {\n");
            sb.Append("  MerchantOrderId: ").Append(MerchantOrderId).Append("\n");
            sb.Append("  ExpectedTotalAmount: ").Append(ExpectedTotalAmount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ExpectedTotalAmount (long) minimum
            if (this.ExpectedTotalAmount < (long)0)
            {
                yield return new ValidationResult("Invalid value for ExpectedTotalAmount, must be a value greater than 0.", new [] { "ExpectedTotalAmount" });
            }

            if (this.Currency != null) {
                // Currency (string) pattern
                Regex regexCurrency = new Regex(@"^[A-Z]{3}$", RegexOptions.CultureInvariant);
                if (!regexCurrency.Match(this.Currency).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Currency, must match a pattern of " + regexCurrency, new [] { "Currency" });
                }
            }

            yield break;
        }
    }

}
