/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// CaptureCheckout422Response
    /// </summary>
    [DataContract(Name = "captureCheckout_422_response")]
    public partial class CaptureCheckout422Response : IValidatableObject
    {
        /// <summary>
        /// Defines Code
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum OrderMismatch for value: order_mismatch
            /// </summary>
            [EnumMember(Value = "order_mismatch")]
            OrderMismatch = 1,

            /// <summary>
            /// Enum AmountMismatch for value: amount_mismatch
            /// </summary>
            [EnumMember(Value = "amount_mismatch")]
            AmountMismatch = 2,

            /// <summary>
            /// Enum CurrencyMismatch for value: currency_mismatch
            /// </summary>
            [EnumMember(Value = "currency_mismatch")]
            CurrencyMismatch = 3,

            /// <summary>
            /// Enum NoActiveSession for value: no_active_session
            /// </summary>
            [EnumMember(Value = "no_active_session")]
            NoActiveSession = 4
        }


        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public CodeEnum Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureCheckout422Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CaptureCheckout422Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureCheckout422Response" /> class.
        /// </summary>
        /// <param name="message">message (required).</param>
        /// <param name="error">error (required).</param>
        /// <param name="code">code (required).</param>
        /// <param name="metadata">metadata.</param>
        public CaptureCheckout422Response(string message = default, string error = default, CodeEnum code = default, Dictionary<string, Object> metadata = default)
        {
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for CaptureCheckout422Response and cannot be null");
            }
            this.Message = message;
            // to ensure "error" is required (not null)
            if (error == null)
            {
                throw new ArgumentNullException("error is a required property for CaptureCheckout422Response and cannot be null");
            }
            this.Error = error;
            this.Code = code;
            this.Metadata = metadata;
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", IsRequired = true, EmitDefaultValue = true)]
        public string Error { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaptureCheckout422Response {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
