/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// CheckoutCancelled
    /// </summary>
    [DataContract(Name = "CheckoutCancelled")]
    public partial class CheckoutCancelled : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutCancelled" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CheckoutCancelled() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutCancelled" /> class.
        /// </summary>
        /// <param name="checkoutUuid">checkoutUuid (required).</param>
        /// <param name="merchantOrderId">merchantOrderId (required).</param>
        /// <param name="status">status (required).</param>
        public CheckoutCancelled(string checkoutUuid = default, string merchantOrderId = default, string status = default)
        {
            // to ensure "checkoutUuid" is required (not null)
            if (checkoutUuid == null)
            {
                throw new ArgumentNullException("checkoutUuid is a required property for CheckoutCancelled and cannot be null");
            }
            this.CheckoutUuid = checkoutUuid;
            // to ensure "merchantOrderId" is required (not null)
            if (merchantOrderId == null)
            {
                throw new ArgumentNullException("merchantOrderId is a required property for CheckoutCancelled and cannot be null");
            }
            this.MerchantOrderId = merchantOrderId;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for CheckoutCancelled and cannot be null");
            }
            this.Status = status;
        }

        /// <summary>
        /// Gets or Sets CheckoutUuid
        /// </summary>
        [DataMember(Name = "checkout_uuid", IsRequired = true, EmitDefaultValue = true)]
        public string CheckoutUuid { get; set; }

        /// <summary>
        /// Gets or Sets MerchantOrderId
        /// </summary>
        [DataMember(Name = "merchant_order_id", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantOrderId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckoutCancelled {\n");
            sb.Append("  CheckoutUuid: ").Append(CheckoutUuid).Append("\n");
            sb.Append("  MerchantOrderId: ").Append(MerchantOrderId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
