/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// CheckoutFee
    /// </summary>
    [DataContract(Name = "CheckoutFee")]
    public partial class CheckoutFee : IValidatableObject
    {
        /// <summary>
        /// Defines FeeType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FeeTypeEnum
        {
            /// <summary>
            /// Enum RefundProtection for value: refund_protection
            /// </summary>
            [EnumMember(Value = "refund_protection")]
            RefundProtection = 1,

            /// <summary>
            /// Enum Surcharge for value: surcharge
            /// </summary>
            [EnumMember(Value = "surcharge")]
            Surcharge = 2,

            /// <summary>
            /// Enum TransactionFee for value: transaction_fee
            /// </summary>
            [EnumMember(Value = "transaction_fee")]
            TransactionFee = 3,

            /// <summary>
            /// Enum ServiceFee for value: service_fee
            /// </summary>
            [EnumMember(Value = "service_fee")]
            ServiceFee = 4,

            /// <summary>
            /// Enum DeliveryFee for value: delivery_fee
            /// </summary>
            [EnumMember(Value = "delivery_fee")]
            DeliveryFee = 5,

            /// <summary>
            /// Enum CarbonOffset for value: carbon_offset
            /// </summary>
            [EnumMember(Value = "carbon_offset")]
            CarbonOffset = 6,

            /// <summary>
            /// Enum Other for value: other
            /// </summary>
            [EnumMember(Value = "other")]
            Other = 7
        }


        /// <summary>
        /// Gets or Sets FeeType
        /// </summary>
        [DataMember(Name = "fee_type", EmitDefaultValue = true)]
        public FeeTypeEnum? FeeType { get; set; }
        /// <summary>
        /// Defines Scope
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ScopeEnum
        {
            /// <summary>
            /// Enum Cart for value: cart
            /// </summary>
            [EnumMember(Value = "cart")]
            Cart = 1,

            /// <summary>
            /// Enum Item for value: item
            /// </summary>
            [EnumMember(Value = "item")]
            Item = 2
        }


        /// <summary>
        /// Gets or Sets Scope
        /// </summary>
        [DataMember(Name = "scope", IsRequired = true, EmitDefaultValue = true)]
        public ScopeEnum Scope { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutFee" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CheckoutFee() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutFee" /> class.
        /// </summary>
        /// <param name="name">name (required).</param>
        /// <param name="description">description.</param>
        /// <param name="feeType">feeType.</param>
        /// <param name="scope">scope (required).</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="appliesTo">appliesTo.</param>
        public CheckoutFee(string name = default, string description = default, FeeTypeEnum? feeType = default, ScopeEnum scope = default, int amount = default, string currency = default, Dictionary<string, Object> metadata = default, List<string> appliesTo = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CheckoutFee and cannot be null");
            }
            this.Name = name;
            this.Scope = scope;
            this.Amount = amount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for CheckoutFee and cannot be null");
            }
            this.Currency = currency;
            this.Description = description;
            this.FeeType = feeType;
            this.Metadata = metadata;
            this.AppliesTo = appliesTo;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public int Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Gets or Sets AppliesTo
        /// </summary>
        [DataMember(Name = "applies_to", EmitDefaultValue = true)]
        public List<string> AppliesTo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckoutFee {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  FeeType: ").Append(FeeType).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  AppliesTo: ").Append(AppliesTo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Amount (int) minimum
            if (this.Amount < (int)0)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.", new [] { "Amount" });
            }

            if (this.Currency != null) {
                // Currency (string) pattern
                Regex regexCurrency = new Regex(@"^[A-Z]{3}$", RegexOptions.CultureInvariant);
                if (!regexCurrency.Match(this.Currency).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Currency, must match a pattern of " + regexCurrency, new [] { "Currency" });
                }
            }

            yield break;
        }
    }

}
