/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// Checkout
    /// </summary>
    [DataContract(Name = "Checkout")]
    public partial class Checkout : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Checkout" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Checkout() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Checkout" /> class.
        /// </summary>
        /// <param name="checkoutUuid">checkoutUuid (required).</param>
        /// <param name="merchantOrderId">merchantOrderId (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="transactionRef">transactionRef (required).</param>
        /// <param name="checkoutUrl">checkoutUrl (required).</param>
        /// <param name="merchantExpiresAt">merchantExpiresAt (required).</param>
        /// <param name="capturedAt">capturedAt (required).</param>
        /// <param name="returnUrl">returnUrl (required).</param>
        /// <param name="cancelUrl">cancelUrl (required).</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="serviceFee">serviceFee (required).</param>
        /// <param name="refundedAmount">refundedAmount (required).</param>
        /// <param name="merchantProcessorFee">merchantProcessorFee (required).</param>
        /// <param name="merchantServiceFee">merchantServiceFee (required).</param>
        /// <param name="lastRefundAt">lastRefundAt (required).</param>
        public Checkout(string checkoutUuid = default, string merchantOrderId = default, string status = default, string transactionRef = default, string checkoutUrl = default, DateTime? merchantExpiresAt = default, DateTime? capturedAt = default, string returnUrl = default, string cancelUrl = default, int amount = default, string currency = default, Fee serviceFee = default, int refundedAmount = default, int merchantProcessorFee = default, int merchantServiceFee = default, DateTime? lastRefundAt = default)
        {
            // to ensure "checkoutUuid" is required (not null)
            if (checkoutUuid == null)
            {
                throw new ArgumentNullException("checkoutUuid is a required property for Checkout and cannot be null");
            }
            this.CheckoutUuid = checkoutUuid;
            // to ensure "merchantOrderId" is required (not null)
            if (merchantOrderId == null)
            {
                throw new ArgumentNullException("merchantOrderId is a required property for Checkout and cannot be null");
            }
            this.MerchantOrderId = merchantOrderId;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for Checkout and cannot be null");
            }
            this.Status = status;
            // to ensure "transactionRef" is required (not null)
            if (transactionRef == null)
            {
                throw new ArgumentNullException("transactionRef is a required property for Checkout and cannot be null");
            }
            this.TransactionRef = transactionRef;
            // to ensure "checkoutUrl" is required (not null)
            if (checkoutUrl == null)
            {
                throw new ArgumentNullException("checkoutUrl is a required property for Checkout and cannot be null");
            }
            this.CheckoutUrl = checkoutUrl;
            // to ensure "merchantExpiresAt" is required (not null)
            if (merchantExpiresAt == null)
            {
                throw new ArgumentNullException("merchantExpiresAt is a required property for Checkout and cannot be null");
            }
            this.MerchantExpiresAt = merchantExpiresAt;
            // to ensure "capturedAt" is required (not null)
            if (capturedAt == null)
            {
                throw new ArgumentNullException("capturedAt is a required property for Checkout and cannot be null");
            }
            this.CapturedAt = capturedAt;
            // to ensure "returnUrl" is required (not null)
            if (returnUrl == null)
            {
                throw new ArgumentNullException("returnUrl is a required property for Checkout and cannot be null");
            }
            this.ReturnUrl = returnUrl;
            // to ensure "cancelUrl" is required (not null)
            if (cancelUrl == null)
            {
                throw new ArgumentNullException("cancelUrl is a required property for Checkout and cannot be null");
            }
            this.CancelUrl = cancelUrl;
            this.Amount = amount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for Checkout and cannot be null");
            }
            this.Currency = currency;
            // to ensure "serviceFee" is required (not null)
            if (serviceFee == null)
            {
                throw new ArgumentNullException("serviceFee is a required property for Checkout and cannot be null");
            }
            this.ServiceFee = serviceFee;
            this.RefundedAmount = refundedAmount;
            this.MerchantProcessorFee = merchantProcessorFee;
            this.MerchantServiceFee = merchantServiceFee;
            // to ensure "lastRefundAt" is required (not null)
            if (lastRefundAt == null)
            {
                throw new ArgumentNullException("lastRefundAt is a required property for Checkout and cannot be null");
            }
            this.LastRefundAt = lastRefundAt;
        }

        /// <summary>
        /// Gets or Sets CheckoutUuid
        /// </summary>
        [DataMember(Name = "checkout_uuid", IsRequired = true, EmitDefaultValue = true)]
        public string CheckoutUuid { get; set; }

        /// <summary>
        /// Gets or Sets MerchantOrderId
        /// </summary>
        [DataMember(Name = "merchant_order_id", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantOrderId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets TransactionRef
        /// </summary>
        [DataMember(Name = "transaction_ref", IsRequired = true, EmitDefaultValue = true)]
        public string TransactionRef { get; set; }

        /// <summary>
        /// Gets or Sets CheckoutUrl
        /// </summary>
        [DataMember(Name = "checkout_url", IsRequired = true, EmitDefaultValue = true)]
        public string CheckoutUrl { get; set; }

        /// <summary>
        /// Gets or Sets MerchantExpiresAt
        /// </summary>
        [DataMember(Name = "merchant_expires_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? MerchantExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets CapturedAt
        /// </summary>
        [DataMember(Name = "captured_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? CapturedAt { get; set; }

        /// <summary>
        /// Gets or Sets ReturnUrl
        /// </summary>
        [DataMember(Name = "return_url", IsRequired = true, EmitDefaultValue = true)]
        public string ReturnUrl { get; set; }

        /// <summary>
        /// Gets or Sets CancelUrl
        /// </summary>
        [DataMember(Name = "cancel_url", IsRequired = true, EmitDefaultValue = true)]
        public string CancelUrl { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public int Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets ServiceFee
        /// </summary>
        [DataMember(Name = "service_fee", IsRequired = true, EmitDefaultValue = true)]
        public Fee ServiceFee { get; set; }

        /// <summary>
        /// Gets or Sets RefundedAmount
        /// </summary>
        [DataMember(Name = "refunded_amount", IsRequired = true, EmitDefaultValue = true)]
        public int RefundedAmount { get; set; }

        /// <summary>
        /// Gets or Sets MerchantProcessorFee
        /// </summary>
        [DataMember(Name = "merchant_processor_fee", IsRequired = true, EmitDefaultValue = true)]
        public int MerchantProcessorFee { get; set; }

        /// <summary>
        /// Gets or Sets MerchantServiceFee
        /// </summary>
        [DataMember(Name = "merchant_service_fee", IsRequired = true, EmitDefaultValue = true)]
        public int MerchantServiceFee { get; set; }

        /// <summary>
        /// Gets or Sets LastRefundAt
        /// </summary>
        [DataMember(Name = "last_refund_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? LastRefundAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Checkout {\n");
            sb.Append("  CheckoutUuid: ").Append(CheckoutUuid).Append("\n");
            sb.Append("  MerchantOrderId: ").Append(MerchantOrderId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TransactionRef: ").Append(TransactionRef).Append("\n");
            sb.Append("  CheckoutUrl: ").Append(CheckoutUrl).Append("\n");
            sb.Append("  MerchantExpiresAt: ").Append(MerchantExpiresAt).Append("\n");
            sb.Append("  CapturedAt: ").Append(CapturedAt).Append("\n");
            sb.Append("  ReturnUrl: ").Append(ReturnUrl).Append("\n");
            sb.Append("  CancelUrl: ").Append(CancelUrl).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  ServiceFee: ").Append(ServiceFee).Append("\n");
            sb.Append("  RefundedAmount: ").Append(RefundedAmount).Append("\n");
            sb.Append("  MerchantProcessorFee: ").Append(MerchantProcessorFee).Append("\n");
            sb.Append("  MerchantServiceFee: ").Append(MerchantServiceFee).Append("\n");
            sb.Append("  LastRefundAt: ").Append(LastRefundAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // RefundedAmount (int) minimum
            if (this.RefundedAmount < (int)0)
            {
                yield return new ValidationResult("Invalid value for RefundedAmount, must be a value greater than or equal to 0.", new [] { "RefundedAmount" });
            }

            // MerchantProcessorFee (int) minimum
            if (this.MerchantProcessorFee < (int)0)
            {
                yield return new ValidationResult("Invalid value for MerchantProcessorFee, must be a value greater than or equal to 0.", new [] { "MerchantProcessorFee" });
            }

            // MerchantServiceFee (int) minimum
            if (this.MerchantServiceFee < (int)0)
            {
                yield return new ValidationResult("Invalid value for MerchantServiceFee, must be a value greater than or equal to 0.", new [] { "MerchantServiceFee" });
            }

            yield break;
        }
    }

}
