/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// CreateCheckoutRequest
    /// </summary>
    [DataContract(Name = "CreateCheckoutRequest")]
    public partial class CreateCheckoutRequest : IValidatableObject
    {
        /// <summary>
        /// Defines AllocationModel
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AllocationModelEnum
        {
            /// <summary>
            /// Enum BasicAmount for value: basic_amount
            /// </summary>
            [EnumMember(Value = "basic_amount")]
            BasicAmount = 1,

            /// <summary>
            /// Enum ItemAssignment for value: item_assignment
            /// </summary>
            [EnumMember(Value = "item_assignment")]
            ItemAssignment = 2
        }


        /// <summary>
        /// Gets or Sets AllocationModel
        /// </summary>
        [DataMember(Name = "allocation_model", EmitDefaultValue = true)]
        public AllocationModelEnum? AllocationModel { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCheckoutRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCheckoutRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCheckoutRequest" /> class.
        /// </summary>
        /// <param name="merchantOrderId">merchantOrderId.</param>
        /// <param name="merchantExpiresAt">merchantExpiresAt.</param>
        /// <param name="totalAmount">totalAmount (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="returnUrl">returnUrl (required).</param>
        /// <param name="cancelUrl">cancelUrl (required).</param>
        /// <param name="items">items (required).</param>
        /// <param name="fees">fees.</param>
        /// <param name="discounts">discounts.</param>
        /// <param name="tax">tax.</param>
        /// <param name="shippingAmount">shippingAmount.</param>
        /// <param name="customerData">customerData.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="allocationModel">allocationModel.</param>
        public CreateCheckoutRequest(string merchantOrderId = default, DateTime? merchantExpiresAt = default, int totalAmount = default, string currency = default, string returnUrl = default, string cancelUrl = default, List<LineItem> items = default, List<CheckoutFee> fees = default, List<CheckoutDiscount> discounts = default, Tax tax = default, int? shippingAmount = default, CustomerData customerData = default, Dictionary<string, Object> metadata = default, AllocationModelEnum? allocationModel = default)
        {
            this.TotalAmount = totalAmount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for CreateCheckoutRequest and cannot be null");
            }
            this.Currency = currency;
            // to ensure "returnUrl" is required (not null)
            if (returnUrl == null)
            {
                throw new ArgumentNullException("returnUrl is a required property for CreateCheckoutRequest and cannot be null");
            }
            this.ReturnUrl = returnUrl;
            // to ensure "cancelUrl" is required (not null)
            if (cancelUrl == null)
            {
                throw new ArgumentNullException("cancelUrl is a required property for CreateCheckoutRequest and cannot be null");
            }
            this.CancelUrl = cancelUrl;
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for CreateCheckoutRequest and cannot be null");
            }
            this.Items = items;
            this.MerchantOrderId = merchantOrderId;
            this.MerchantExpiresAt = merchantExpiresAt;
            this.Fees = fees;
            this.Discounts = discounts;
            this.Tax = tax;
            this.ShippingAmount = shippingAmount;
            this.CustomerData = customerData;
            this.Metadata = metadata;
            this.AllocationModel = allocationModel;
        }

        /// <summary>
        /// Gets or Sets MerchantOrderId
        /// </summary>
        [DataMember(Name = "merchant_order_id", EmitDefaultValue = true)]
        public string MerchantOrderId { get; set; }

        /// <summary>
        /// Gets or Sets MerchantExpiresAt
        /// </summary>
        [DataMember(Name = "merchant_expires_at", EmitDefaultValue = true)]
        public DateTime? MerchantExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets TotalAmount
        /// </summary>
        [DataMember(Name = "total_amount", IsRequired = true, EmitDefaultValue = true)]
        public long TotalAmount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets ReturnUrl
        /// </summary>
        [DataMember(Name = "return_url", IsRequired = true, EmitDefaultValue = true)]
        public string ReturnUrl { get; set; }

        /// <summary>
        /// Gets or Sets CancelUrl
        /// </summary>
        [DataMember(Name = "cancel_url", IsRequired = true, EmitDefaultValue = true)]
        public string CancelUrl { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<LineItem> Items { get; set; }

        /// <summary>
        /// Gets or Sets Fees
        /// </summary>
        [DataMember(Name = "fees", EmitDefaultValue = true)]
        public List<CheckoutFee> Fees { get; set; }

        /// <summary>
        /// Gets or Sets Discounts
        /// </summary>
        [DataMember(Name = "discounts", EmitDefaultValue = true)]
        public List<CheckoutDiscount> Discounts { get; set; }

        /// <summary>
        /// Gets or Sets Tax
        /// </summary>
        [DataMember(Name = "tax", EmitDefaultValue = true)]
        public Tax Tax { get; set; }

        /// <summary>
        /// Gets or Sets ShippingAmount
        /// </summary>
        [DataMember(Name = "shipping_amount", EmitDefaultValue = true)]
        public int? ShippingAmount { get; set; }

        /// <summary>
        /// Gets or Sets CustomerData
        /// </summary>
        [DataMember(Name = "customer_data", EmitDefaultValue = true)]
        public CustomerData CustomerData { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = true)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCheckoutRequest {\n");
            sb.Append("  MerchantOrderId: ").Append(MerchantOrderId).Append("\n");
            sb.Append("  MerchantExpiresAt: ").Append(MerchantExpiresAt).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  ReturnUrl: ").Append(ReturnUrl).Append("\n");
            sb.Append("  CancelUrl: ").Append(CancelUrl).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  Fees: ").Append(Fees).Append("\n");
            sb.Append("  Discounts: ").Append(Discounts).Append("\n");
            sb.Append("  Tax: ").Append(Tax).Append("\n");
            sb.Append("  ShippingAmount: ").Append(ShippingAmount).Append("\n");
            sb.Append("  CustomerData: ").Append(CustomerData).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  AllocationModel: ").Append(AllocationModel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TotalAmount (long) minimum
            if (this.TotalAmount < (long)0)
            {
                yield return new ValidationResult("Invalid value for TotalAmount, must be a value greater than 0.", new [] { "TotalAmount" });
            }

            if (this.Currency != null) {
                // Currency (string) pattern
                Regex regexCurrency = new Regex(@"^[A-Z]{3}$", RegexOptions.CultureInvariant);
                if (!regexCurrency.Match(this.Currency).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Currency, must match a pattern of " + regexCurrency, new [] { "Currency" });
                }
            }

            // ShippingAmount (int?) minimum
            if (this.ShippingAmount < (int?)0)
            {
                yield return new ValidationResult("Invalid value for ShippingAmount, must be a value greater than or equal to 0.", new [] { "ShippingAmount" });
            }

            yield break;
        }
    }

}
