/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// CreateRefundRequest
    /// </summary>
    [DataContract(Name = "CreateRefundRequest")]
    public partial class CreateRefundRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRefundRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateRefundRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRefundRequest" /> class.
        /// </summary>
        /// <param name="reason">Free-text reason; forwarded to Stripe as refund metadata..</param>
        /// <param name="merchantRefundRef">Idempotency key scoped to the merchant. Repeating the same value returns the existing refund. (required).</param>
        public CreateRefundRequest(string reason = default, string merchantRefundRef = default)
        {
            // to ensure "merchantRefundRef" is required (not null)
            if (merchantRefundRef == null)
            {
                throw new ArgumentNullException("merchantRefundRef is a required property for CreateRefundRequest and cannot be null");
            }
            this.MerchantRefundRef = merchantRefundRef;
            this.Reason = reason;
        }

        /// <summary>
        /// Free-text reason; forwarded to Stripe as refund metadata.
        /// </summary>
        /// <value>Free-text reason; forwarded to Stripe as refund metadata.</value>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public string Reason { get; set; }

        /// <summary>
        /// Idempotency key scoped to the merchant. Repeating the same value returns the existing refund.
        /// </summary>
        /// <value>Idempotency key scoped to the merchant. Repeating the same value returns the existing refund.</value>
        [DataMember(Name = "merchant_refund_ref", IsRequired = true, EmitDefaultValue = true)]
        public string MerchantRefundRef { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateRefundRequest {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  MerchantRefundRef: ").Append(MerchantRefundRef).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Reason (string) maxLength
            if (this.Reason != null && this.Reason.Length > 500)
            {
                yield return new ValidationResult("Invalid value for Reason, length must be less than 500.", new [] { "Reason" });
            }

            // MerchantRefundRef (string) maxLength
            if (this.MerchantRefundRef != null && this.MerchantRefundRef.Length > 255)
            {
                yield return new ValidationResult("Invalid value for MerchantRefundRef, length must be less than 255.", new [] { "MerchantRefundRef" });
            }

            // MerchantRefundRef (string) minLength
            if (this.MerchantRefundRef != null && this.MerchantRefundRef.Length < 1)
            {
                yield return new ValidationResult("Invalid value for MerchantRefundRef, length must be greater than 1.", new [] { "MerchantRefundRef" });
            }

            yield break;
        }
    }

}
