/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// Fee
    /// </summary>
    [DataContract(Name = "Fee")]
    public partial class Fee : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Fee" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Fee() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Fee" /> class.
        /// </summary>
        /// <param name="gross">gross (required).</param>
        /// <param name="discount">discount (required).</param>
        /// <param name="net">net (required).</param>
        /// <param name="breakdown">breakdown (required).</param>
        public Fee(int gross = default, int discount = default, int net = default, List<FeeBreakdownLine> breakdown = default)
        {
            this.Gross = gross;
            this.Discount = discount;
            this.Net = net;
            // to ensure "breakdown" is required (not null)
            if (breakdown == null)
            {
                throw new ArgumentNullException("breakdown is a required property for Fee and cannot be null");
            }
            this.Breakdown = breakdown;
        }

        /// <summary>
        /// Gets or Sets Gross
        /// </summary>
        [DataMember(Name = "gross", IsRequired = true, EmitDefaultValue = true)]
        public int Gross { get; set; }

        /// <summary>
        /// Gets or Sets Discount
        /// </summary>
        [DataMember(Name = "discount", IsRequired = true, EmitDefaultValue = true)]
        public int Discount { get; set; }

        /// <summary>
        /// Gets or Sets Net
        /// </summary>
        [DataMember(Name = "net", IsRequired = true, EmitDefaultValue = true)]
        public int Net { get; set; }

        /// <summary>
        /// Gets or Sets Breakdown
        /// </summary>
        [DataMember(Name = "breakdown", IsRequired = true, EmitDefaultValue = true)]
        public List<FeeBreakdownLine> Breakdown { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Fee {\n");
            sb.Append("  Gross: ").Append(Gross).Append("\n");
            sb.Append("  Discount: ").Append(Discount).Append("\n");
            sb.Append("  Net: ").Append(Net).Append("\n");
            sb.Append("  Breakdown: ").Append(Breakdown).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Gross (int) minimum
            if (this.Gross < (int)0)
            {
                yield return new ValidationResult("Invalid value for Gross, must be a value greater than or equal to 0.", new [] { "Gross" });
            }

            // Discount (int) minimum
            if (this.Discount < (int)0)
            {
                yield return new ValidationResult("Invalid value for Discount, must be a value greater than or equal to 0.", new [] { "Discount" });
            }

            // Net (int) minimum
            if (this.Net < (int)0)
            {
                yield return new ValidationResult("Invalid value for Net, must be a value greater than or equal to 0.", new [] { "Net" });
            }

            yield break;
        }
    }

}
