/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// FoodBeverageLineItem
    /// </summary>
    [DataContract(Name = "FoodBeverageLineItem")]
    public partial class FoodBeverageLineItem : IValidatableObject
    {
        /// <summary>
        /// Defines Category
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CategoryEnum
        {
            /// <summary>
            /// Enum FoodBeverage for value: food_beverage
            /// </summary>
            [EnumMember(Value = "food_beverage")]
            FoodBeverage = 1
        }


        /// <summary>
        /// Gets or Sets Category
        /// </summary>
        [DataMember(Name = "category", IsRequired = true, EmitDefaultValue = true)]
        public CategoryEnum Category { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FoodBeverageLineItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FoodBeverageLineItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FoodBeverageLineItem" /> class.
        /// </summary>
        /// <param name="itemRef">itemRef (required).</param>
        /// <param name="parentRef">parentRef.</param>
        /// <param name="sku">sku.</param>
        /// <param name="name">name (required).</param>
        /// <param name="description">description.</param>
        /// <param name="imageUrl">imageUrl.</param>
        /// <param name="quantity">quantity (required).</param>
        /// <param name="unitPrice">unitPrice (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="category">category (required).</param>
        public FoodBeverageLineItem(string itemRef = default, string parentRef = default, string sku = default, string name = default, string description = default, string imageUrl = default, int quantity = default, int unitPrice = default, string currency = default, CategoryEnum category = default)
        {
            // to ensure "itemRef" is required (not null)
            if (itemRef == null)
            {
                throw new ArgumentNullException("itemRef is a required property for FoodBeverageLineItem and cannot be null");
            }
            this.ItemRef = itemRef;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for FoodBeverageLineItem and cannot be null");
            }
            this.Name = name;
            this.Quantity = quantity;
            this.UnitPrice = unitPrice;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for FoodBeverageLineItem and cannot be null");
            }
            this.Currency = currency;
            this.Category = category;
            this.ParentRef = parentRef;
            this.Sku = sku;
            this.Description = description;
            this.ImageUrl = imageUrl;
        }

        /// <summary>
        /// Gets or Sets ItemRef
        /// </summary>
        [DataMember(Name = "item_ref", IsRequired = true, EmitDefaultValue = true)]
        public string ItemRef { get; set; }

        /// <summary>
        /// Gets or Sets ParentRef
        /// </summary>
        [DataMember(Name = "parent_ref", EmitDefaultValue = true)]
        public string ParentRef { get; set; }

        /// <summary>
        /// Gets or Sets Sku
        /// </summary>
        [DataMember(Name = "sku", EmitDefaultValue = true)]
        public string Sku { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [DataMember(Name = "image_url", EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name = "quantity", IsRequired = true, EmitDefaultValue = true)]
        public long Quantity { get; set; }

        /// <summary>
        /// Gets or Sets UnitPrice
        /// </summary>
        [DataMember(Name = "unit_price", IsRequired = true, EmitDefaultValue = true)]
        public int UnitPrice { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FoodBeverageLineItem {\n");
            sb.Append("  ItemRef: ").Append(ItemRef).Append("\n");
            sb.Append("  ParentRef: ").Append(ParentRef).Append("\n");
            sb.Append("  Sku: ").Append(Sku).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  UnitPrice: ").Append(UnitPrice).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ItemRef (string) minLength
            if (this.ItemRef != null && this.ItemRef.Length < 1)
            {
                yield return new ValidationResult("Invalid value for ItemRef, length must be greater than 1.", new [] { "ItemRef" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Quantity (long) minimum
            if (this.Quantity < (long)0)
            {
                yield return new ValidationResult("Invalid value for Quantity, must be a value greater than 0.", new [] { "Quantity" });
            }

            // UnitPrice (int) minimum
            if (this.UnitPrice < (int)0)
            {
                yield return new ValidationResult("Invalid value for UnitPrice, must be a value greater than or equal to 0.", new [] { "UnitPrice" });
            }

            if (this.Currency != null) {
                // Currency (string) pattern
                Regex regexCurrency = new Regex(@"^[A-Z]{3}$", RegexOptions.CultureInvariant);
                if (!regexCurrency.Match(this.Currency).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Currency, must match a pattern of " + regexCurrency, new [] { "Currency" });
                }
            }

            yield break;
        }
    }

}
