/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// LineItem
    /// </summary>
    [JsonConverter(typeof(LineItemJsonConverter))]
    [DataContract(Name = "LineItem")]
    public partial class LineItem : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LineItem" /> class
        /// with the <see cref="TicketLineItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TicketLineItem.</param>
        public LineItem(TicketLineItem actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LineItem" /> class
        /// with the <see cref="PhysicalGoodsLineItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of PhysicalGoodsLineItem.</param>
        public LineItem(PhysicalGoodsLineItem actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LineItem" /> class
        /// with the <see cref="ServiceLineItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ServiceLineItem.</param>
        public LineItem(ServiceLineItem actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LineItem" /> class
        /// with the <see cref="DigitalGoodsLineItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DigitalGoodsLineItem.</param>
        public LineItem(DigitalGoodsLineItem actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LineItem" /> class
        /// with the <see cref="FoodBeverageLineItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of FoodBeverageLineItem.</param>
        public LineItem(FoodBeverageLineItem actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LineItem" /> class
        /// with the <see cref="DonationLineItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DonationLineItem.</param>
        public LineItem(DonationLineItem actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LineItem" /> class
        /// with the <see cref="OtherLineItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of OtherLineItem.</param>
        public LineItem(OtherLineItem actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(DigitalGoodsLineItem) || value is DigitalGoodsLineItem)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(DonationLineItem) || value is DonationLineItem)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(FoodBeverageLineItem) || value is FoodBeverageLineItem)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(OtherLineItem) || value is OtherLineItem)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(PhysicalGoodsLineItem) || value is PhysicalGoodsLineItem)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ServiceLineItem) || value is ServiceLineItem)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(TicketLineItem) || value is TicketLineItem)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: DigitalGoodsLineItem, DonationLineItem, FoodBeverageLineItem, OtherLineItem, PhysicalGoodsLineItem, ServiceLineItem, TicketLineItem");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `TicketLineItem`. If the actual instance is not `TicketLineItem`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TicketLineItem</returns>
        public TicketLineItem GetTicketLineItem()
        {
            return (TicketLineItem)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `PhysicalGoodsLineItem`. If the actual instance is not `PhysicalGoodsLineItem`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of PhysicalGoodsLineItem</returns>
        public PhysicalGoodsLineItem GetPhysicalGoodsLineItem()
        {
            return (PhysicalGoodsLineItem)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `ServiceLineItem`. If the actual instance is not `ServiceLineItem`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ServiceLineItem</returns>
        public ServiceLineItem GetServiceLineItem()
        {
            return (ServiceLineItem)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DigitalGoodsLineItem`. If the actual instance is not `DigitalGoodsLineItem`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DigitalGoodsLineItem</returns>
        public DigitalGoodsLineItem GetDigitalGoodsLineItem()
        {
            return (DigitalGoodsLineItem)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `FoodBeverageLineItem`. If the actual instance is not `FoodBeverageLineItem`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of FoodBeverageLineItem</returns>
        public FoodBeverageLineItem GetFoodBeverageLineItem()
        {
            return (FoodBeverageLineItem)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `DonationLineItem`. If the actual instance is not `DonationLineItem`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DonationLineItem</returns>
        public DonationLineItem GetDonationLineItem()
        {
            return (DonationLineItem)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `OtherLineItem`. If the actual instance is not `OtherLineItem`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of OtherLineItem</returns>
        public OtherLineItem GetOtherLineItem()
        {
            return (OtherLineItem)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LineItem {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, LineItem.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of LineItem
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of LineItem</returns>
        public static LineItem FromJson(string jsonString)
        {
            LineItem newLineItem = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newLineItem;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DigitalGoodsLineItem).GetProperty("AdditionalProperties") == null)
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<DigitalGoodsLineItem>(jsonString, LineItem.SerializerSettings));
                }
                else
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<DigitalGoodsLineItem>(jsonString, LineItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DigitalGoodsLineItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DigitalGoodsLineItem: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DonationLineItem).GetProperty("AdditionalProperties") == null)
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<DonationLineItem>(jsonString, LineItem.SerializerSettings));
                }
                else
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<DonationLineItem>(jsonString, LineItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DonationLineItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DonationLineItem: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(FoodBeverageLineItem).GetProperty("AdditionalProperties") == null)
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<FoodBeverageLineItem>(jsonString, LineItem.SerializerSettings));
                }
                else
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<FoodBeverageLineItem>(jsonString, LineItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("FoodBeverageLineItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into FoodBeverageLineItem: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(OtherLineItem).GetProperty("AdditionalProperties") == null)
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<OtherLineItem>(jsonString, LineItem.SerializerSettings));
                }
                else
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<OtherLineItem>(jsonString, LineItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("OtherLineItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into OtherLineItem: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(PhysicalGoodsLineItem).GetProperty("AdditionalProperties") == null)
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<PhysicalGoodsLineItem>(jsonString, LineItem.SerializerSettings));
                }
                else
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<PhysicalGoodsLineItem>(jsonString, LineItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("PhysicalGoodsLineItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into PhysicalGoodsLineItem: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(ServiceLineItem).GetProperty("AdditionalProperties") == null)
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<ServiceLineItem>(jsonString, LineItem.SerializerSettings));
                }
                else
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<ServiceLineItem>(jsonString, LineItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("ServiceLineItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ServiceLineItem: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TicketLineItem).GetProperty("AdditionalProperties") == null)
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<TicketLineItem>(jsonString, LineItem.SerializerSettings));
                }
                else
                {
                    newLineItem = new LineItem(JsonConvert.DeserializeObject<TicketLineItem>(jsonString, LineItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("TicketLineItem");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into TicketLineItem: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newLineItem;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for LineItem
    /// </summary>
    public class LineItemJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(LineItem).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return LineItem.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return LineItem.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
