/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// Settlement
    /// </summary>
    [DataContract(Name = "Settlement")]
    public partial class Settlement : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Settlement" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Settlement() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Settlement" /> class.
        /// </summary>
        /// <param name="uuid">uuid (required).</param>
        /// <param name="merchantUuid">merchantUuid (required).</param>
        /// <param name="periodFrom">periodFrom (required).</param>
        /// <param name="periodTo">periodTo (required).</param>
        /// <param name="idempotencyKey">idempotencyKey (required).</param>
        /// <param name="merchantPayableAmount">merchantPayableAmount (required).</param>
        /// <param name="settledAmount">settledAmount (required).</param>
        /// <param name="currency">currency (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="stripeTransferId">stripeTransferId (required).</param>
        /// <param name="notes">notes (required).</param>
        /// <param name="settledAt">settledAt (required).</param>
        /// <param name="expiresAt">expiresAt (required).</param>
        /// <param name="reviewedByUserUuid">reviewedByUserUuid (required).</param>
        /// <param name="reviewedAt">reviewedAt (required).</param>
        /// <param name="rejectionReason">rejectionReason (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public Settlement(Guid uuid = default, Guid merchantUuid = default, DateTime periodFrom = default, DateTime periodTo = default, string idempotencyKey = default, int merchantPayableAmount = default, int settledAmount = default, string currency = default, string status = default, string stripeTransferId = default, string notes = default, DateTime? settledAt = default, DateTime? expiresAt = default, Guid? reviewedByUserUuid = default, DateTime? reviewedAt = default, string rejectionReason = default, DateTime createdAt = default, DateTime updatedAt = default)
        {
            this.Uuid = uuid;
            this.MerchantUuid = merchantUuid;
            this.PeriodFrom = periodFrom;
            this.PeriodTo = periodTo;
            // to ensure "idempotencyKey" is required (not null)
            if (idempotencyKey == null)
            {
                throw new ArgumentNullException("idempotencyKey is a required property for Settlement and cannot be null");
            }
            this.IdempotencyKey = idempotencyKey;
            this.MerchantPayableAmount = merchantPayableAmount;
            this.SettledAmount = settledAmount;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for Settlement and cannot be null");
            }
            this.Currency = currency;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for Settlement and cannot be null");
            }
            this.Status = status;
            // to ensure "stripeTransferId" is required (not null)
            if (stripeTransferId == null)
            {
                throw new ArgumentNullException("stripeTransferId is a required property for Settlement and cannot be null");
            }
            this.StripeTransferId = stripeTransferId;
            // to ensure "notes" is required (not null)
            if (notes == null)
            {
                throw new ArgumentNullException("notes is a required property for Settlement and cannot be null");
            }
            this.Notes = notes;
            // to ensure "settledAt" is required (not null)
            if (settledAt == null)
            {
                throw new ArgumentNullException("settledAt is a required property for Settlement and cannot be null");
            }
            this.SettledAt = settledAt;
            // to ensure "expiresAt" is required (not null)
            if (expiresAt == null)
            {
                throw new ArgumentNullException("expiresAt is a required property for Settlement and cannot be null");
            }
            this.ExpiresAt = expiresAt;
            // to ensure "reviewedByUserUuid" is required (not null)
            if (reviewedByUserUuid == null)
            {
                throw new ArgumentNullException("reviewedByUserUuid is a required property for Settlement and cannot be null");
            }
            this.ReviewedByUserUuid = reviewedByUserUuid;
            // to ensure "reviewedAt" is required (not null)
            if (reviewedAt == null)
            {
                throw new ArgumentNullException("reviewedAt is a required property for Settlement and cannot be null");
            }
            this.ReviewedAt = reviewedAt;
            // to ensure "rejectionReason" is required (not null)
            if (rejectionReason == null)
            {
                throw new ArgumentNullException("rejectionReason is a required property for Settlement and cannot be null");
            }
            this.RejectionReason = rejectionReason;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>
        [DataMember(Name = "uuid", IsRequired = true, EmitDefaultValue = true)]
        public Guid Uuid { get; set; }

        /// <summary>
        /// Gets or Sets MerchantUuid
        /// </summary>
        [DataMember(Name = "merchant_uuid", IsRequired = true, EmitDefaultValue = true)]
        public Guid MerchantUuid { get; set; }

        /// <summary>
        /// Gets or Sets PeriodFrom
        /// </summary>
        [DataMember(Name = "period_from", IsRequired = true, EmitDefaultValue = true)]
        public DateTime PeriodFrom { get; set; }

        /// <summary>
        /// Gets or Sets PeriodTo
        /// </summary>
        [DataMember(Name = "period_to", IsRequired = true, EmitDefaultValue = true)]
        public DateTime PeriodTo { get; set; }

        /// <summary>
        /// Gets or Sets IdempotencyKey
        /// </summary>
        [DataMember(Name = "idempotency_key", IsRequired = true, EmitDefaultValue = true)]
        public string IdempotencyKey { get; set; }

        /// <summary>
        /// Gets or Sets MerchantPayableAmount
        /// </summary>
        [DataMember(Name = "merchant_payable_amount", IsRequired = true, EmitDefaultValue = true)]
        public int MerchantPayableAmount { get; set; }

        /// <summary>
        /// Gets or Sets SettledAmount
        /// </summary>
        [DataMember(Name = "settled_amount", IsRequired = true, EmitDefaultValue = true)]
        public int SettledAmount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets StripeTransferId
        /// </summary>
        [DataMember(Name = "stripe_transfer_id", IsRequired = true, EmitDefaultValue = true)]
        public string StripeTransferId { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name = "notes", IsRequired = true, EmitDefaultValue = true)]
        public string Notes { get; set; }

        /// <summary>
        /// Gets or Sets SettledAt
        /// </summary>
        [DataMember(Name = "settled_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? SettledAt { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [DataMember(Name = "expires_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? ExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets ReviewedByUserUuid
        /// </summary>
        [DataMember(Name = "reviewed_by_user_uuid", IsRequired = true, EmitDefaultValue = true)]
        public Guid? ReviewedByUserUuid { get; set; }

        /// <summary>
        /// Gets or Sets ReviewedAt
        /// </summary>
        [DataMember(Name = "reviewed_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime? ReviewedAt { get; set; }

        /// <summary>
        /// Gets or Sets RejectionReason
        /// </summary>
        [DataMember(Name = "rejection_reason", IsRequired = true, EmitDefaultValue = true)]
        public string RejectionReason { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Settlement {\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  MerchantUuid: ").Append(MerchantUuid).Append("\n");
            sb.Append("  PeriodFrom: ").Append(PeriodFrom).Append("\n");
            sb.Append("  PeriodTo: ").Append(PeriodTo).Append("\n");
            sb.Append("  IdempotencyKey: ").Append(IdempotencyKey).Append("\n");
            sb.Append("  MerchantPayableAmount: ").Append(MerchantPayableAmount).Append("\n");
            sb.Append("  SettledAmount: ").Append(SettledAmount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StripeTransferId: ").Append(StripeTransferId).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  SettledAt: ").Append(SettledAt).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  ReviewedByUserUuid: ").Append(ReviewedByUserUuid).Append("\n");
            sb.Append("  ReviewedAt: ").Append(ReviewedAt).Append("\n");
            sb.Append("  RejectionReason: ").Append(RejectionReason).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Currency (string) maxLength
            if (this.Currency != null && this.Currency.Length > 3)
            {
                yield return new ValidationResult("Invalid value for Currency, length must be less than 3.", new [] { "Currency" });
            }

            // Currency (string) minLength
            if (this.Currency != null && this.Currency.Length < 3)
            {
                yield return new ValidationResult("Invalid value for Currency, length must be greater than 3.", new [] { "Currency" });
            }

            yield break;
        }
    }

}
