/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// TicketSeating
    /// </summary>
    [DataContract(Name = "TicketSeating")]
    public partial class TicketSeating : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TicketSeating" /> class.
        /// </summary>
        /// <param name="section">section.</param>
        /// <param name="row">row.</param>
        /// <param name="seat">seat.</param>
        /// <param name="allocation">allocation.</param>
        public TicketSeating(string section = default, string row = default, string seat = default, Dictionary<string, Object> allocation = default)
        {
            this.Section = section;
            this.Row = row;
            this.Seat = seat;
            this.Allocation = allocation;
        }

        /// <summary>
        /// Gets or Sets Section
        /// </summary>
        [DataMember(Name = "section", EmitDefaultValue = false)]
        public string Section { get; set; }

        /// <summary>
        /// Gets or Sets Row
        /// </summary>
        [DataMember(Name = "row", EmitDefaultValue = false)]
        public string Row { get; set; }

        /// <summary>
        /// Gets or Sets Seat
        /// </summary>
        [DataMember(Name = "seat", EmitDefaultValue = false)]
        public string Seat { get; set; }

        /// <summary>
        /// Gets or Sets Allocation
        /// </summary>
        [DataMember(Name = "allocation", EmitDefaultValue = false)]
        public Dictionary<string, Object> Allocation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TicketSeating {\n");
            sb.Append("  Section: ").Append(Section).Append("\n");
            sb.Append("  Row: ").Append(Row).Append("\n");
            sb.Append("  Seat: ").Append(Seat).Append("\n");
            sb.Append("  Allocation: ").Append(Allocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
