/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = MaytesApiClient.Client.FileParameter;
using OpenAPIDateConverter = MaytesApiClient.Client.OpenAPIDateConverter;

namespace MaytesApiClient.Model
{
    /// <summary>
    /// TicketCustomData
    /// </summary>
    [DataContract(Name = "TicketCustomData")]
    public partial class TicketCustomData : IValidatableObject
    {
        /// <summary>
        /// Defines DeliveryMode
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DeliveryModeEnum
        {
            /// <summary>
            /// Enum Email for value: email
            /// </summary>
            [EnumMember(Value = "email")]
            Email = 1,

            /// <summary>
            /// Enum Sms for value: sms
            /// </summary>
            [EnumMember(Value = "sms")]
            Sms = 2,

            /// <summary>
            /// Enum Post for value: post
            /// </summary>
            [EnumMember(Value = "post")]
            Post = 3,

            /// <summary>
            /// Enum AtVenue for value: at_venue
            /// </summary>
            [EnumMember(Value = "at_venue")]
            AtVenue = 4
        }


        /// <summary>
        /// Gets or Sets DeliveryMode
        /// </summary>
        [DataMember(Name = "delivery_mode", EmitDefaultValue = false)]
        public DeliveryModeEnum? DeliveryMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TicketCustomData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TicketCustomData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TicketCustomData" /> class.
        /// </summary>
        /// <param name="eventId">eventId (required).</param>
        /// <param name="eventStartAt">eventStartAt (required).</param>
        /// <param name="timezone">timezone (required).</param>
        /// <param name="ticketClass">ticketClass.</param>
        /// <param name="name">name.</param>
        /// <param name="eventEndAt">eventEndAt.</param>
        /// <param name="deliveryMode">deliveryMode.</param>
        /// <param name="venueName">venueName.</param>
        /// <param name="venueAddress">venueAddress.</param>
        /// <param name="seating">seating.</param>
        /// <param name="termsUrl">termsUrl.</param>
        /// <param name="attendeeRequired">attendeeRequired.</param>
        public TicketCustomData(string eventId = default, DateTime eventStartAt = default, string timezone = default, string ticketClass = default, string name = default, DateTime eventEndAt = default, DeliveryModeEnum? deliveryMode = default, string venueName = default, Dictionary<string, Object> venueAddress = default, TicketSeating seating = default, string termsUrl = default, bool attendeeRequired = default)
        {
            // to ensure "eventId" is required (not null)
            if (eventId == null)
            {
                throw new ArgumentNullException("eventId is a required property for TicketCustomData and cannot be null");
            }
            this.EventId = eventId;
            this.EventStartAt = eventStartAt;
            // to ensure "timezone" is required (not null)
            if (timezone == null)
            {
                throw new ArgumentNullException("timezone is a required property for TicketCustomData and cannot be null");
            }
            this.Timezone = timezone;
            this.TicketClass = ticketClass;
            this.Name = name;
            this.EventEndAt = eventEndAt;
            this.DeliveryMode = deliveryMode;
            this.VenueName = venueName;
            this.VenueAddress = venueAddress;
            this.Seating = seating;
            this.TermsUrl = termsUrl;
            this.AttendeeRequired = attendeeRequired;
        }

        /// <summary>
        /// Gets or Sets EventId
        /// </summary>
        [DataMember(Name = "event_id", IsRequired = true, EmitDefaultValue = true)]
        public string EventId { get; set; }

        /// <summary>
        /// Gets or Sets EventStartAt
        /// </summary>
        [DataMember(Name = "event_start_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime EventStartAt { get; set; }

        /// <summary>
        /// Gets or Sets Timezone
        /// </summary>
        [DataMember(Name = "timezone", IsRequired = true, EmitDefaultValue = true)]
        public string Timezone { get; set; }

        /// <summary>
        /// Gets or Sets TicketClass
        /// </summary>
        [DataMember(Name = "ticket_class", EmitDefaultValue = false)]
        public string TicketClass { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets EventEndAt
        /// </summary>
        [DataMember(Name = "event_end_at", EmitDefaultValue = false)]
        public DateTime EventEndAt { get; set; }

        /// <summary>
        /// Gets or Sets VenueName
        /// </summary>
        [DataMember(Name = "venue_name", EmitDefaultValue = false)]
        public string VenueName { get; set; }

        /// <summary>
        /// Gets or Sets VenueAddress
        /// </summary>
        [DataMember(Name = "venue_address", EmitDefaultValue = false)]
        public Dictionary<string, Object> VenueAddress { get; set; }

        /// <summary>
        /// Gets or Sets Seating
        /// </summary>
        [DataMember(Name = "seating", EmitDefaultValue = false)]
        public TicketSeating Seating { get; set; }

        /// <summary>
        /// Gets or Sets TermsUrl
        /// </summary>
        [DataMember(Name = "terms_url", EmitDefaultValue = false)]
        public string TermsUrl { get; set; }

        /// <summary>
        /// Gets or Sets AttendeeRequired
        /// </summary>
        [DataMember(Name = "attendee_required", EmitDefaultValue = true)]
        public bool AttendeeRequired { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TicketCustomData {\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  EventStartAt: ").Append(EventStartAt).Append("\n");
            sb.Append("  Timezone: ").Append(Timezone).Append("\n");
            sb.Append("  TicketClass: ").Append(TicketClass).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  EventEndAt: ").Append(EventEndAt).Append("\n");
            sb.Append("  DeliveryMode: ").Append(DeliveryMode).Append("\n");
            sb.Append("  VenueName: ").Append(VenueName).Append("\n");
            sb.Append("  VenueAddress: ").Append(VenueAddress).Append("\n");
            sb.Append("  Seating: ").Append(Seating).Append("\n");
            sb.Append("  TermsUrl: ").Append(TermsUrl).Append("\n");
            sb.Append("  AttendeeRequired: ").Append(AttendeeRequired).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
