/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CancelCheckoutRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelCheckoutRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CancelCheckoutRequest
        //private CancelCheckoutRequest instance;

        public CancelCheckoutRequestTests()
        {
            // TODO uncomment below to create an instance of CancelCheckoutRequest
            //instance = new CancelCheckoutRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CancelCheckoutRequest
        /// </summary>
        [Fact]
        public void CancelCheckoutRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CancelCheckoutRequest
            //Assert.IsType<CancelCheckoutRequest>(instance);
        }

        /// <summary>
        /// Test the property 'MerchantOrderId'
        /// </summary>
        [Fact]
        public void MerchantOrderIdTest()
        {
            // TODO unit test for the property 'MerchantOrderId'
        }
    }
}
