/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CancelCheckoutResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelCheckoutResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CancelCheckoutResponse
        //private CancelCheckoutResponse instance;

        public CancelCheckoutResponseTests()
        {
            // TODO uncomment below to create an instance of CancelCheckoutResponse
            //instance = new CancelCheckoutResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CancelCheckoutResponse
        /// </summary>
        [Fact]
        public void CancelCheckoutResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CancelCheckoutResponse
            //Assert.IsType<CancelCheckoutResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
