/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CancelCheckout409Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CancelCheckout409ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CancelCheckout409Response
        //private CancelCheckout409Response instance;

        public CancelCheckout409ResponseTests()
        {
            // TODO uncomment below to create an instance of CancelCheckout409Response
            //instance = new CancelCheckout409Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CancelCheckout409Response
        /// </summary>
        [Fact]
        public void CancelCheckout409ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CancelCheckout409Response
            //Assert.IsType<CancelCheckout409Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
