/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CheckoutCreated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutCreatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckoutCreated
        //private CheckoutCreated instance;

        public CheckoutCreatedTests()
        {
            // TODO uncomment below to create an instance of CheckoutCreated
            //instance = new CheckoutCreated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutCreated
        /// </summary>
        [Fact]
        public void CheckoutCreatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckoutCreated
            //Assert.IsType<CheckoutCreated>(instance);
        }

        /// <summary>
        /// Test the property 'CheckoutUuid'
        /// </summary>
        [Fact]
        public void CheckoutUuidTest()
        {
            // TODO unit test for the property 'CheckoutUuid'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CheckoutUrl'
        /// </summary>
        [Fact]
        public void CheckoutUrlTest()
        {
            // TODO unit test for the property 'CheckoutUrl'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
    }
}
