/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Checkout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Checkout
        //private Checkout instance;

        public CheckoutTests()
        {
            // TODO uncomment below to create an instance of Checkout
            //instance = new Checkout();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Checkout
        /// </summary>
        [Fact]
        public void CheckoutInstanceTest()
        {
            // TODO uncomment below to test "IsType" Checkout
            //Assert.IsType<Checkout>(instance);
        }

        /// <summary>
        /// Test the property 'CheckoutUuid'
        /// </summary>
        [Fact]
        public void CheckoutUuidTest()
        {
            // TODO unit test for the property 'CheckoutUuid'
        }

        /// <summary>
        /// Test the property 'MerchantOrderId'
        /// </summary>
        [Fact]
        public void MerchantOrderIdTest()
        {
            // TODO unit test for the property 'MerchantOrderId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'TransactionRef'
        /// </summary>
        [Fact]
        public void TransactionRefTest()
        {
            // TODO unit test for the property 'TransactionRef'
        }

        /// <summary>
        /// Test the property 'CheckoutUrl'
        /// </summary>
        [Fact]
        public void CheckoutUrlTest()
        {
            // TODO unit test for the property 'CheckoutUrl'
        }

        /// <summary>
        /// Test the property 'MerchantExpiresAt'
        /// </summary>
        [Fact]
        public void MerchantExpiresAtTest()
        {
            // TODO unit test for the property 'MerchantExpiresAt'
        }

        /// <summary>
        /// Test the property 'CapturedAt'
        /// </summary>
        [Fact]
        public void CapturedAtTest()
        {
            // TODO unit test for the property 'CapturedAt'
        }

        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Fact]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }

        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Fact]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'ServiceFee'
        /// </summary>
        [Fact]
        public void ServiceFeeTest()
        {
            // TODO unit test for the property 'ServiceFee'
        }

        /// <summary>
        /// Test the property 'RefundedAmount'
        /// </summary>
        [Fact]
        public void RefundedAmountTest()
        {
            // TODO unit test for the property 'RefundedAmount'
        }

        /// <summary>
        /// Test the property 'MerchantProcessorFee'
        /// </summary>
        [Fact]
        public void MerchantProcessorFeeTest()
        {
            // TODO unit test for the property 'MerchantProcessorFee'
        }

        /// <summary>
        /// Test the property 'MerchantServiceFee'
        /// </summary>
        [Fact]
        public void MerchantServiceFeeTest()
        {
            // TODO unit test for the property 'MerchantServiceFee'
        }

        /// <summary>
        /// Test the property 'LastRefundAt'
        /// </summary>
        [Fact]
        public void LastRefundAtTest()
        {
            // TODO unit test for the property 'LastRefundAt'
        }
    }
}
