/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CheckoutCancelled
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutCancelledTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckoutCancelled
        //private CheckoutCancelled instance;

        public CheckoutCancelledTests()
        {
            // TODO uncomment below to create an instance of CheckoutCancelled
            //instance = new CheckoutCancelled();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutCancelled
        /// </summary>
        [Fact]
        public void CheckoutCancelledInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckoutCancelled
            //Assert.IsType<CheckoutCancelled>(instance);
        }

        /// <summary>
        /// Test the property 'CheckoutUuid'
        /// </summary>
        [Fact]
        public void CheckoutUuidTest()
        {
            // TODO unit test for the property 'CheckoutUuid'
        }

        /// <summary>
        /// Test the property 'MerchantOrderId'
        /// </summary>
        [Fact]
        public void MerchantOrderIdTest()
        {
            // TODO unit test for the property 'MerchantOrderId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
