/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CheckoutCaptured
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutCapturedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckoutCaptured
        //private CheckoutCaptured instance;

        public CheckoutCapturedTests()
        {
            // TODO uncomment below to create an instance of CheckoutCaptured
            //instance = new CheckoutCaptured();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutCaptured
        /// </summary>
        [Fact]
        public void CheckoutCapturedInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckoutCaptured
            //Assert.IsType<CheckoutCaptured>(instance);
        }

        /// <summary>
        /// Test the property 'CheckoutUuid'
        /// </summary>
        [Fact]
        public void CheckoutUuidTest()
        {
            // TODO unit test for the property 'CheckoutUuid'
        }

        /// <summary>
        /// Test the property 'MerchantOrderId'
        /// </summary>
        [Fact]
        public void MerchantOrderIdTest()
        {
            // TODO unit test for the property 'MerchantOrderId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CapturedAt'
        /// </summary>
        [Fact]
        public void CapturedAtTest()
        {
            // TODO unit test for the property 'CapturedAt'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
    }
}
