/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreateRefundRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateRefundRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateRefundRequest
        //private CreateRefundRequest instance;

        public CreateRefundRequestTests()
        {
            // TODO uncomment below to create an instance of CreateRefundRequest
            //instance = new CreateRefundRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateRefundRequest
        /// </summary>
        [Fact]
        public void CreateRefundRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateRefundRequest
            //Assert.IsType<CreateRefundRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'MerchantRefundRef'
        /// </summary>
        [Fact]
        public void MerchantRefundRefTest()
        {
            // TODO unit test for the property 'MerchantRefundRef'
        }
    }
}
