/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCheckoutRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCheckoutRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCheckoutRequest
        //private CreateCheckoutRequest instance;

        public CreateCheckoutRequestTests()
        {
            // TODO uncomment below to create an instance of CreateCheckoutRequest
            //instance = new CreateCheckoutRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCheckoutRequest
        /// </summary>
        [Fact]
        public void CreateCheckoutRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCheckoutRequest
            //Assert.IsType<CreateCheckoutRequest>(instance);
        }

        /// <summary>
        /// Test the property 'MerchantOrderId'
        /// </summary>
        [Fact]
        public void MerchantOrderIdTest()
        {
            // TODO unit test for the property 'MerchantOrderId'
        }

        /// <summary>
        /// Test the property 'MerchantExpiresAt'
        /// </summary>
        [Fact]
        public void MerchantExpiresAtTest()
        {
            // TODO unit test for the property 'MerchantExpiresAt'
        }

        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Fact]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Fact]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }

        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Fact]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Fees'
        /// </summary>
        [Fact]
        public void FeesTest()
        {
            // TODO unit test for the property 'Fees'
        }

        /// <summary>
        /// Test the property 'Discounts'
        /// </summary>
        [Fact]
        public void DiscountsTest()
        {
            // TODO unit test for the property 'Discounts'
        }

        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Fact]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }

        /// <summary>
        /// Test the property 'ShippingAmount'
        /// </summary>
        [Fact]
        public void ShippingAmountTest()
        {
            // TODO unit test for the property 'ShippingAmount'
        }

        /// <summary>
        /// Test the property 'CustomerData'
        /// </summary>
        [Fact]
        public void CustomerDataTest()
        {
            // TODO unit test for the property 'CustomerData'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'AllocationModel'
        /// </summary>
        [Fact]
        public void AllocationModelTest()
        {
            // TODO unit test for the property 'AllocationModel'
        }
    }
}
