/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCheckoutResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCheckoutResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCheckoutResponse
        //private CreateCheckoutResponse instance;

        public CreateCheckoutResponseTests()
        {
            // TODO uncomment below to create an instance of CreateCheckoutResponse
            //instance = new CreateCheckoutResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCheckoutResponse
        /// </summary>
        [Fact]
        public void CreateCheckoutResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCheckoutResponse
            //Assert.IsType<CreateCheckoutResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
