/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DigitalGoodsLineItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DigitalGoodsLineItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DigitalGoodsLineItem
        //private DigitalGoodsLineItem instance;

        public DigitalGoodsLineItemTests()
        {
            // TODO uncomment below to create an instance of DigitalGoodsLineItem
            //instance = new DigitalGoodsLineItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DigitalGoodsLineItem
        /// </summary>
        [Fact]
        public void DigitalGoodsLineItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" DigitalGoodsLineItem
            //Assert.IsType<DigitalGoodsLineItem>(instance);
        }

        /// <summary>
        /// Test the property 'ItemRef'
        /// </summary>
        [Fact]
        public void ItemRefTest()
        {
            // TODO unit test for the property 'ItemRef'
        }

        /// <summary>
        /// Test the property 'ParentRef'
        /// </summary>
        [Fact]
        public void ParentRefTest()
        {
            // TODO unit test for the property 'ParentRef'
        }

        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Fact]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Fact]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Fact]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
    }
}
