/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Fee
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Fee
        //private Fee instance;

        public FeeTests()
        {
            // TODO uncomment below to create an instance of Fee
            //instance = new Fee();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Fee
        /// </summary>
        [Fact]
        public void FeeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Fee
            //Assert.IsType<Fee>(instance);
        }

        /// <summary>
        /// Test the property 'Gross'
        /// </summary>
        [Fact]
        public void GrossTest()
        {
            // TODO unit test for the property 'Gross'
        }

        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Fact]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }

        /// <summary>
        /// Test the property 'Net'
        /// </summary>
        [Fact]
        public void NetTest()
        {
            // TODO unit test for the property 'Net'
        }

        /// <summary>
        /// Test the property 'Breakdown'
        /// </summary>
        [Fact]
        public void BreakdownTest()
        {
            // TODO unit test for the property 'Breakdown'
        }
    }
}
