/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ListSettlementsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListSettlementsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListSettlementsResponse
        //private ListSettlementsResponse instance;

        public ListSettlementsResponseTests()
        {
            // TODO uncomment below to create an instance of ListSettlementsResponse
            //instance = new ListSettlementsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListSettlementsResponse
        /// </summary>
        [Fact]
        public void ListSettlementsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListSettlementsResponse
            //Assert.IsType<ListSettlementsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
