/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PhysicalGoodsCustomData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PhysicalGoodsCustomDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PhysicalGoodsCustomData
        //private PhysicalGoodsCustomData instance;

        public PhysicalGoodsCustomDataTests()
        {
            // TODO uncomment below to create an instance of PhysicalGoodsCustomData
            //instance = new PhysicalGoodsCustomData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PhysicalGoodsCustomData
        /// </summary>
        [Fact]
        public void PhysicalGoodsCustomDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" PhysicalGoodsCustomData
            //Assert.IsType<PhysicalGoodsCustomData>(instance);
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Fact]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
    }
}
