/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ServiceCustomData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ServiceCustomDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ServiceCustomData
        //private ServiceCustomData instance;

        public ServiceCustomDataTests()
        {
            // TODO uncomment below to create an instance of ServiceCustomData
            //instance = new ServiceCustomData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ServiceCustomData
        /// </summary>
        [Fact]
        public void ServiceCustomDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ServiceCustomData
            //Assert.IsType<ServiceCustomData>(instance);
        }

        /// <summary>
        /// Test the property 'ServiceType'
        /// </summary>
        [Fact]
        public void ServiceTypeTest()
        {
            // TODO unit test for the property 'ServiceType'
        }
    }
}
