/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing Settlement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SettlementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Settlement
        //private Settlement instance;

        public SettlementTests()
        {
            // TODO uncomment below to create an instance of Settlement
            //instance = new Settlement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Settlement
        /// </summary>
        [Fact]
        public void SettlementInstanceTest()
        {
            // TODO uncomment below to test "IsType" Settlement
            //Assert.IsType<Settlement>(instance);
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }

        /// <summary>
        /// Test the property 'MerchantUuid'
        /// </summary>
        [Fact]
        public void MerchantUuidTest()
        {
            // TODO unit test for the property 'MerchantUuid'
        }

        /// <summary>
        /// Test the property 'PeriodFrom'
        /// </summary>
        [Fact]
        public void PeriodFromTest()
        {
            // TODO unit test for the property 'PeriodFrom'
        }

        /// <summary>
        /// Test the property 'PeriodTo'
        /// </summary>
        [Fact]
        public void PeriodToTest()
        {
            // TODO unit test for the property 'PeriodTo'
        }

        /// <summary>
        /// Test the property 'IdempotencyKey'
        /// </summary>
        [Fact]
        public void IdempotencyKeyTest()
        {
            // TODO unit test for the property 'IdempotencyKey'
        }

        /// <summary>
        /// Test the property 'MerchantPayableAmount'
        /// </summary>
        [Fact]
        public void MerchantPayableAmountTest()
        {
            // TODO unit test for the property 'MerchantPayableAmount'
        }

        /// <summary>
        /// Test the property 'SettledAmount'
        /// </summary>
        [Fact]
        public void SettledAmountTest()
        {
            // TODO unit test for the property 'SettledAmount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StripeTransferId'
        /// </summary>
        [Fact]
        public void StripeTransferIdTest()
        {
            // TODO unit test for the property 'StripeTransferId'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'SettledAt'
        /// </summary>
        [Fact]
        public void SettledAtTest()
        {
            // TODO unit test for the property 'SettledAt'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'ReviewedByUserUuid'
        /// </summary>
        [Fact]
        public void ReviewedByUserUuidTest()
        {
            // TODO unit test for the property 'ReviewedByUserUuid'
        }

        /// <summary>
        /// Test the property 'ReviewedAt'
        /// </summary>
        [Fact]
        public void ReviewedAtTest()
        {
            // TODO unit test for the property 'ReviewedAt'
        }

        /// <summary>
        /// Test the property 'RejectionReason'
        /// </summary>
        [Fact]
        public void RejectionReasonTest()
        {
            // TODO unit test for the property 'RejectionReason'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
