/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TicketSeating
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TicketSeatingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TicketSeating
        //private TicketSeating instance;

        public TicketSeatingTests()
        {
            // TODO uncomment below to create an instance of TicketSeating
            //instance = new TicketSeating();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TicketSeating
        /// </summary>
        [Fact]
        public void TicketSeatingInstanceTest()
        {
            // TODO uncomment below to test "IsType" TicketSeating
            //Assert.IsType<TicketSeating>(instance);
        }

        /// <summary>
        /// Test the property 'Section'
        /// </summary>
        [Fact]
        public void SectionTest()
        {
            // TODO unit test for the property 'Section'
        }

        /// <summary>
        /// Test the property 'Row'
        /// </summary>
        [Fact]
        public void RowTest()
        {
            // TODO unit test for the property 'Row'
        }

        /// <summary>
        /// Test the property 'Seat'
        /// </summary>
        [Fact]
        public void SeatTest()
        {
            // TODO unit test for the property 'Seat'
        }

        /// <summary>
        /// Test the property 'Allocation'
        /// </summary>
        [Fact]
        public void AllocationTest()
        {
            // TODO unit test for the property 'Allocation'
        }
    }
}
