/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MaytesApiClient.Model;
using MaytesApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MaytesApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TicketCustomData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TicketCustomDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TicketCustomData
        //private TicketCustomData instance;

        public TicketCustomDataTests()
        {
            // TODO uncomment below to create an instance of TicketCustomData
            //instance = new TicketCustomData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TicketCustomData
        /// </summary>
        [Fact]
        public void TicketCustomDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" TicketCustomData
            //Assert.IsType<TicketCustomData>(instance);
        }

        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Fact]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }

        /// <summary>
        /// Test the property 'EventStartAt'
        /// </summary>
        [Fact]
        public void EventStartAtTest()
        {
            // TODO unit test for the property 'EventStartAt'
        }

        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

        /// <summary>
        /// Test the property 'TicketClass'
        /// </summary>
        [Fact]
        public void TicketClassTest()
        {
            // TODO unit test for the property 'TicketClass'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'EventEndAt'
        /// </summary>
        [Fact]
        public void EventEndAtTest()
        {
            // TODO unit test for the property 'EventEndAt'
        }

        /// <summary>
        /// Test the property 'DeliveryMode'
        /// </summary>
        [Fact]
        public void DeliveryModeTest()
        {
            // TODO unit test for the property 'DeliveryMode'
        }

        /// <summary>
        /// Test the property 'VenueName'
        /// </summary>
        [Fact]
        public void VenueNameTest()
        {
            // TODO unit test for the property 'VenueName'
        }

        /// <summary>
        /// Test the property 'VenueAddress'
        /// </summary>
        [Fact]
        public void VenueAddressTest()
        {
            // TODO unit test for the property 'VenueAddress'
        }

        /// <summary>
        /// Test the property 'Seating'
        /// </summary>
        [Fact]
        public void SeatingTest()
        {
            // TODO unit test for the property 'Seating'
        }

        /// <summary>
        /// Test the property 'TermsUrl'
        /// </summary>
        [Fact]
        public void TermsUrlTest()
        {
            // TODO unit test for the property 'TermsUrl'
        }

        /// <summary>
        /// Test the property 'AttendeeRequired'
        /// </summary>
        [Fact]
        public void AttendeeRequiredTest()
        {
            // TODO unit test for the property 'AttendeeRequired'
        }
    }
}
