/*
 * Maytes API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using MaytesApiClient.Client;
using MaytesApiClient.Api;
// uncomment below to import models
//using MaytesApiClient.Model;

namespace MaytesApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests : IDisposable
    {
        private DefaultApi instance;

        public DefaultApiTests()
        {
            instance = new DefaultApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DefaultApi
            //Assert.IsType<DefaultApi>(instance);
        }

        /// <summary>
        /// Test CancelCheckout
        /// </summary>
        [Fact]
        public void CancelCheckoutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string checkoutUuid = null;
            //CancelCheckoutRequest cancelCheckoutRequest = null;
            //var response = instance.CancelCheckout(checkoutUuid, cancelCheckoutRequest);
            //Assert.IsType<CancelCheckoutResponse>(response);
        }

        /// <summary>
        /// Test CaptureCheckout
        /// </summary>
        [Fact]
        public void CaptureCheckoutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string checkoutUuid = null;
            //CaptureCheckoutRequest captureCheckoutRequest = null;
            //var response = instance.CaptureCheckout(checkoutUuid, captureCheckoutRequest);
            //Assert.IsType<CaptureCheckoutResponse>(response);
        }

        /// <summary>
        /// Test CreateCheckout
        /// </summary>
        [Fact]
        public void CreateCheckoutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateCheckoutRequest createCheckoutRequest = null;
            //var response = instance.CreateCheckout(createCheckoutRequest);
            //Assert.IsType<CreateCheckoutResponse>(response);
        }

        /// <summary>
        /// Test GetCheckout
        /// </summary>
        [Fact]
        public void GetCheckoutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string checkoutUuid = null;
            //string? merchantOrderId = null;
            //var response = instance.GetCheckout(checkoutUuid, merchantOrderId);
            //Assert.IsType<GetCheckoutResponse>(response);
        }

        /// <summary>
        /// Test GetHealth
        /// </summary>
        [Fact]
        public void GetHealthTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetHealth();
            //Assert.IsType<HealthResponse>(response);
        }

        /// <summary>
        /// Test GetOAuthToken
        /// </summary>
        [Fact]
        public void GetOAuthTokenTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OAuthTokenRequest oAuthTokenRequest = null;
            //var response = instance.GetOAuthToken(oAuthTokenRequest);
            //Assert.IsType<OAuthTokenResponse>(response);
        }

        /// <summary>
        /// Test GetSettlement
        /// </summary>
        [Fact]
        public void GetSettlementTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uuid = null;
            //var response = instance.GetSettlement(uuid);
            //Assert.IsType<GetSettlementResponse>(response);
        }

        /// <summary>
        /// Test ListSettlements
        /// </summary>
        [Fact]
        public void ListSettlementsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object? offset = null;
            //Object? limit = null;
            //string? sortDir = null;
            //string? sortBy = null;
            //Object? createdBefore = null;
            //Object? createdAfter = null;
            //string? status = null;
            //var response = instance.ListSettlements(offset, limit, sortDir, sortBy, createdBefore, createdAfter, status);
            //Assert.IsType<ListSettlementsResponse>(response);
        }

        /// <summary>
        /// Test RefundCheckout
        /// </summary>
        [Fact]
        public void RefundCheckoutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string checkoutUuid = null;
            //CreateRefundRequest createRefundRequest = null;
            //instance.RefundCheckout(checkoutUuid, createRefundRequest);
        }
    }
}
